### ISSUE TITLE
The end of the animation kind of goes back and forth

### ISSUE THREAD

**Issue by antoninadert** [Itrulia/nova-skeletons#1]
At the end of the animation, the $nova-color-skeleton-end color goes a little back and forth instead of just going to the end and starting again.

This is especially visible with higher contrasts

I hope you can fix this one

**Comment by Itrulia** [comment]
Didnt see this, thanks! will take a look

**Comment by Itrulia** [comment]
You can now `npm update @itrulia/nova-skeletons` and it should be fixed :)
